//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "backend/database/schema_create_cache.h"

#include <atomic>
#include <cstdint>
#include <memory>
#include <string>
#include <thread>  // NOLINT
#include <utility>
#include <vector>

#include "google/protobuf/descriptor.pb.h"
#include "google/spanner/admin/database/v1/common.pb.h"
#include "googlesql/public/types/type_factory.h"
#include "googlesql/public/value.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "googlesql/base/testing/status_matchers.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/flags/commandlineflag.h"
#include "absl/flags/flag.h"
#include "absl/flags/reflection.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/string_view.h"
#include "absl/synchronization/notification.h"
#include "absl/time/clock.h"
#include "backend/database/database.h"
#include "backend/schema/catalog/column.h"
#include "backend/schema/catalog/schema.h"
#include "backend/schema/catalog/sequence.h"
#include "backend/schema/catalog/table.h"
#include "backend/schema/printer/print_ddl.h"
#include "backend/database/change_stream/change_stream_partition_churner.h"
#include "backend/schema/updater/schema_updater.h"
#include "common/clock.h"
#include "common/feature_flags.h"
#include "tests/common/scoped_feature_flags_setter.h"
#include "tests/common/schema_constructor.h"
#include "tests/common/test.pb.h"

namespace google {
namespace spanner {
namespace emulator {
namespace backend {
namespace {

namespace database_api = ::google::spanner::admin::database::v1;

using ::googlesql_base::testing::IsOkAndHolds;
using ::testing::ElementsAreArray;
using ::testing::Not;

std::string ProtoDescriptors() {
  google::protobuf::FileDescriptorSet files;
  ::emulator::tests::common::Simple::descriptor()->file()->CopyTo(
      files.add_file());
  return files.SerializeAsString();
}

// Every kind of node CopySchema edits: factory-owned column types (arrays,
// protos, enums), a view, a sequence, an identity column's sequence, and a
// change stream.
const std::vector<std::string>& GoogleSqlDdl() {
  static const auto* ddl = new std::vector<std::string>{
      R"(CREATE PROTO BUNDLE (emulator.tests.common.Simple,
                              emulator.tests.common.TestEnum))",
      R"(CREATE SEQUENCE seq OPTIONS (sequence_kind = 'bit_reversed_positive'))",
      R"(CREATE TABLE t (
           id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE seq)),
           ident INT64 GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
           s STRING(MAX),
           a ARRAY<STRING(MAX)>,
           p emulator.tests.common.Simple,
           e emulator.tests.common.TestEnum,
           ap ARRAY<emulator.tests.common.Simple>,
           u STRING(MAX) AS (UPPER(s)) STORED,
         ) PRIMARY KEY (id))",
      R"(CREATE TABLE c (
           id INT64 NOT NULL,
           k INT64 NOT NULL,
           v FLOAT64,
         ) PRIMARY KEY (id, k), INTERLEAVE IN PARENT t ON DELETE CASCADE)",
      "CREATE INDEX t_by_s ON t(s) STORING (a)",
      "CREATE VIEW v SQL SECURITY INVOKER AS SELECT t.id, t.a FROM t",
      "CREATE CHANGE STREAM cs FOR t",
      "ALTER TABLE c ADD CONSTRAINT fk FOREIGN KEY (k) REFERENCES t (id)",
  };
  return *ddl;
}

const std::vector<std::string>& PostgresDdl() {
  static const auto* ddl = new std::vector<std::string>{
      "CREATE SEQUENCE seq BIT_REVERSED_POSITIVE",
      R"(CREATE TABLE t (
           id bigint NOT NULL DEFAULT nextval('seq'),
           ident bigint GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
           s varchar,
           a varchar[],
           n numeric,
           PRIMARY KEY (id)))",
      "CREATE INDEX t_by_s ON t(s) INCLUDE (a)",
      "CREATE VIEW v SQL SECURITY INVOKER AS SELECT t.id, t.a FROM t",
      "CREATE CHANGE STREAM cs FOR t",
  };
  return *ddl;
}

SchemaChangeOperation Operation(database_api::DatabaseDialect dialect,
                                const std::string& proto_descriptors) {
  return SchemaChangeOperation{
      .statements = dialect == database_api::DatabaseDialect::POSTGRESQL
                        ? PostgresDdl()
                        : GoogleSqlDdl(),
      .proto_descriptor_bytes =
          dialect == database_api::DatabaseDialect::POSTGRESQL
              ? absl::string_view()
              : absl::string_view(proto_descriptors),
      .database_dialect = dialect,
  };
}

std::vector<std::string> Ddl(const Database& database) {
  absl::StatusOr<std::vector<std::string>> ddl =
      PrintDDLStatements(database.GetLatestSchema());
  EXPECT_THAT(ddl, googlesql_base::testing::IsOk());
  return ddl.value_or(std::vector<std::string>{});
}

// The IDs and PostgreSQL OIDs of every table and column, which a database
// assigns from its own counters.
std::vector<std::string> Ids(const Database& database) {
  std::vector<std::string> ids;
  for (const Table* table : database.GetLatestSchema()->tables()) {
    ids.push_back(absl::StrCat(table->Name(), "=", table->id(), "/",
                               table->postgresql_oid().value_or(0)));
    for (const Column* column : table->columns()) {
      ids.push_back(absl::StrCat(column->FullName(), "=", column->id(), "/",
                                 column->postgresql_oid().value_or(0)));
    }
  }
  return ids;
}

std::vector<int64_t> DrawSequence(const Sequence* sequence, int n) {
  std::vector<int64_t> values;
  for (int i = 0; i < n; ++i) {
    absl::StatusOr<googlesql::Value> value = sequence->GetNextSequenceValue();
    EXPECT_THAT(value, googlesql_base::testing::IsOk());
    values.push_back(value.ok() ? value->int64_value() : -1);
  }
  return values;
}

const Sequence* IdentitySequence(const Database& database) {
  const Column* column =
      database.GetLatestSchema()->FindTable("t")->FindColumn("ident");
  return static_cast<const Sequence*>(column->sequences_used().at(0));
}

class SchemaCreateCacheTest
    : public ::testing::TestWithParam<database_api::DatabaseDialect> {
 protected:
  void SetUp() override {
    previous_ = SchemaCreateCache::SetGlobalForTesting(&cache_);
  }
  void TearDown() override { SchemaCreateCache::SetGlobalForTesting(previous_); }

  SchemaChangeOperation operation() const {
    return Operation(GetParam(), proto_descriptors_);
  }

  absl::StatusOr<std::unique_ptr<Database>> Create(
      const SchemaChangeOperation& operation, bool use_cache = true) {
    SchemaCreateCache* cache =
        SchemaCreateCache::SetGlobalForTesting(use_cache ? &cache_ : nullptr);
    absl::StatusOr<std::unique_ptr<Database>> database =
        Database::Create(&clock_, "db", operation);
    SchemaCreateCache::SetGlobalForTesting(cache);
    return database;
  }

  Clock clock_;
  const std::string proto_descriptors_ = ProtoDescriptors();
  SchemaCreateCache cache_{4};
  SchemaCreateCache* previous_ = nullptr;
};

// A database created from the cache has the schema, IDs and OIDs of one
// created from DDL, and so does the same schema change applied to each.
TEST_P(SchemaCreateCacheTest, CachedDatabaseMatchesUncached) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> uncached,
                       Create(operation(), /*use_cache=*/false));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> first, Create(operation()));
  EXPECT_EQ(cache_.misses(), 1);
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> cached, Create(operation()));
  EXPECT_EQ(cache_.hits(), 1);
  EXPECT_EQ(cache_.copies(), 1);

  EXPECT_THAT(Ddl(*cached), ElementsAreArray(Ddl(*uncached)));
  EXPECT_THAT(Ids(*cached), ElementsAreArray(Ids(*uncached)));
  EXPECT_THAT(Ddl(*first), ElementsAreArray(Ddl(*uncached)));

  // New tables and columns take the next IDs and OIDs, as they would on the
  // uncached database.
  std::vector<std::string> change =
      GetParam() == database_api::DatabaseDialect::POSTGRESQL
          ? std::vector<std::string>{"ALTER TABLE t ADD COLUMN x bigint",
                                     "CREATE TABLE n (k bigint PRIMARY KEY)",
                                     "CREATE INDEX t_by_x ON t(x)",
                                     "DROP INDEX t_by_s",
                                     "ALTER SEQUENCE seq SKIP RANGE 1 1000"}
          : std::vector<std::string>{
                "ALTER TABLE t ADD COLUMN x INT64",
                "CREATE TABLE n (k INT64) PRIMARY KEY (k)",
                "CREATE INDEX t_by_x ON t(x)", "DROP INDEX t_by_s",
                "ALTER SEQUENCE seq SET OPTIONS (skip_range_min = 1, "
                "skip_range_max = 1000)"};
  for (Database* database : {uncached.get(), cached.get()}) {
    int succeeded = 0;
    absl::Time commit_timestamp;
    absl::Status backfill_status;
    GOOGLESQL_ASSERT_OK(database->UpdateSchema(
        SchemaChangeOperation{.statements = change,
                              .database_dialect = GetParam()},
        &succeeded, &commit_timestamp, &backfill_status));
    GOOGLESQL_ASSERT_OK(backfill_status);
    EXPECT_EQ(succeeded, change.size());
  }
  EXPECT_THAT(Ddl(*cached), ElementsAreArray(Ddl(*uncached)));
  EXPECT_THAT(Ids(*cached), ElementsAreArray(Ids(*uncached)));
}

// A failing request is never cached and fails as it does without the cache.
TEST_P(SchemaCreateCacheTest, FailedCreateIsNotCached) {
  SchemaChangeOperation failing = operation();
  std::vector<std::string> statements(failing.statements.begin(),
                                      failing.statements.end());
  statements.push_back("CREATE TABLE t (k INT64) PRIMARY KEY (k)");
  failing.statements = statements;

  absl::Status uncached = Create(failing, /*use_cache=*/false).status();
  ASSERT_FALSE(uncached.ok());
  for (int i = 0; i < 3; ++i) {
    absl::Status cached = Create(failing).status();
    EXPECT_EQ(cached.code(), uncached.code());
    EXPECT_EQ(cached.message(), uncached.message());
  }
  EXPECT_EQ(cache_.size(), 0);
  EXPECT_EQ(cache_.hits(), 0);
}

// Each database starts its sequences where a new database's start, and draws
// from them independently of every other database.
TEST_P(SchemaCreateCacheTest, SequencesAreIndependent) {
  constexpr int kValues = 50;
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> uncached,
                       Create(operation(), /*use_cache=*/false));
  const std::vector<int64_t> expected = DrawSequence(
      uncached->GetLatestSchema()->FindSequence("seq"), kValues);
  const std::vector<int64_t> expected_identity =
      DrawSequence(IdentitySequence(*uncached), kValues);

  constexpr int kDatabases = 8;
  std::vector<std::unique_ptr<Database>> databases;
  for (int i = 0; i < kDatabases; ++i) {
    GOOGLESQL_ASSERT_OK_AND_ASSIGN(databases.emplace_back(), Create(operation()));
  }
  EXPECT_EQ(cache_.hits(), kDatabases - 1);
  EXPECT_EQ(cache_.copies(), kDatabases - 1);
  std::vector<std::thread> threads;
  for (const std::unique_ptr<Database>& database : databases) {
    threads.emplace_back([&, db = database.get()] {
      EXPECT_EQ(DrawSequence(db->GetLatestSchema()->FindSequence("seq"),
                             kValues),
                expected);
      EXPECT_EQ(DrawSequence(IdentitySequence(*db), kValues),
                expected_identity);
    });
  }
  for (std::thread& thread : threads) thread.join();
}

// Concurrent creates of the same DDL, some missing and some hitting, all get
// the same schema, while other keys evict the entry.
TEST_P(SchemaCreateCacheTest, ConcurrentCreatesOfTheSameDdl) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> uncached,
                       Create(operation(), /*use_cache=*/false));
  const std::vector<std::string> expected = Ddl(*uncached);
  std::vector<std::thread> threads;
  for (int t = 0; t < 16; ++t) {
    threads.emplace_back([&, t] {
      for (int i = 0; i < 3; ++i) {
        SchemaChangeOperation op = operation();
        std::vector<std::string> statements(op.statements.begin(),
                                            op.statements.end());
        if (t % 4 == 3) {
          // A different key, to evict entries.
          statements.push_back(absl::StrCat(
              GetParam() == database_api::DatabaseDialect::POSTGRESQL
                  ? "CREATE TABLE extra (k bigint PRIMARY KEY, v"
                  : "CREATE TABLE extra (k INT64, v",
              t, i,
              GetParam() == database_api::DatabaseDialect::POSTGRESQL
                  ? " bigint)"
                  : " INT64) PRIMARY KEY (k)"));
          op.statements = statements;
        }
        absl::StatusOr<std::unique_ptr<Database>> database =
            Database::Create(&clock_, absl::StrCat("db", t, "_", i), op);
        ASSERT_THAT(database, googlesql_base::testing::IsOk());
        if (t % 4 != 3) {
          EXPECT_THAT(Ddl(**database), ElementsAreArray(expected));
          EXPECT_THAT(DrawSequence((*database)->GetLatestSchema()->FindSequence(
                                       "seq"),
                                   3),
                      Not(testing::IsEmpty()));
        }
      }
    });
  }
  for (std::thread& thread : threads) thread.join();
  EXPECT_GT(cache_.hits(), 0);
  EXPECT_EQ(cache_.copies(), cache_.hits());
  EXPECT_EQ(cache_.fallbacks(), 0);
}

// A database created from an entry keeps working after the entry is evicted
// and the database the entry came from is dropped.
TEST_P(SchemaCreateCacheTest, DatabaseOutlivesItsEntry) {
  SchemaCreateCache small(1);
  SchemaCreateCache::SetGlobalForTesting(&small);
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> source,
                       Database::Create(&clock_, "source", operation()));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> cached,
                       Database::Create(&clock_, "db", operation()));
  EXPECT_EQ(small.hits(), 1);
  EXPECT_EQ(small.copies(), 1);
  const std::vector<std::string> expected = Ddl(*source);

  SchemaChangeOperation other = operation();
  std::vector<std::string> statements(other.statements.begin(),
                                      other.statements.end());
  statements.pop_back();
  other.statements = statements;
  GOOGLESQL_ASSERT_OK(Database::Create(&clock_, "other", other).status());
  EXPECT_EQ(small.size(), 1);
  source.reset();

  EXPECT_THAT(Ddl(*cached), ElementsAreArray(expected));
  EXPECT_THAT(DrawSequence(cached->GetLatestSchema()->FindSequence("seq"), 3),
              Not(testing::IsEmpty()));
  int succeeded = 0;
  absl::Time commit_timestamp;
  absl::Status backfill_status;
  GOOGLESQL_ASSERT_OK(cached->UpdateSchema(
      SchemaChangeOperation{
          .statements = {GetParam() == database_api::DatabaseDialect::POSTGRESQL
                             ? "ALTER TABLE t ADD COLUMN x varchar[]"
                             : "ALTER TABLE t ADD COLUMN x ARRAY<INT64>"},
          .database_dialect = GetParam()},
      &succeeded, &commit_timestamp, &backfill_status));
  EXPECT_EQ(succeeded, 1);

  // The same request misses now, and creates from DDL.
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::unique_ptr<Database> again,
                       Database::Create(&clock_, "db", operation()));
  EXPECT_EQ(small.hits(), 1);
  EXPECT_EQ(small.copies(), 1);
  EXPECT_THAT(Ddl(*again), ElementsAreArray(expected));
  SchemaCreateCache::SetGlobalForTesting(&cache_);
}

INSTANTIATE_TEST_SUITE_P(
    Dialects, SchemaCreateCacheTest,
    ::testing::Values(database_api::DatabaseDialect::GOOGLE_STANDARD_SQL,
                      database_api::DatabaseDialect::POSTGRESQL),
    [](const ::testing::TestParamInfo<database_api::DatabaseDialect>& info) {
      return database_api::DatabaseDialect_Name(info.param);
    });

// A copy depends on nothing of its source: the source and its type factory
// are destroyed before the copy is used.
TEST(CopySchemaTest, CopyOwnsItsTypes) {
  auto source_factory = std::make_unique<googlesql::TypeFactory>();
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::unique_ptr<const Schema> source,
      test::CreateSchemaFromDDL(GoogleSqlDdl(), source_factory.get(),
                                ProtoDescriptors()));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(std::vector<std::string> expected,
                       PrintDDLStatements(source.get()));
  const std::string source_sequence_id =
      source->FindSequence("seq")->id();
  std::vector<std::string> types;
  for (const Column* column : source->FindTable("t")->columns()) {
    types.push_back(column->GetType()->DebugString());
  }

  googlesql::TypeFactory copy_factory;
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::unique_ptr<const Schema> copy,
      CopySchema(*source, &copy_factory, "copy", "seq_copy_", absl::Now()));
  source.reset();
  source_factory.reset();

  EXPECT_EQ(copy->database_id(), "copy");
  EXPECT_THAT(PrintDDLStatements(copy.get()), IsOkAndHolds(expected));
  EXPECT_NE(copy->FindSequence("seq")->id(), source_sequence_id);
  EXPECT_TRUE(absl::StartsWith(copy->FindSequence("seq")->id(), "seq_copy_"));
  std::vector<std::string> copied_types;
  for (const Column* column : copy->FindTable("t")->columns()) {
    copied_types.push_back(column->GetType()->DebugString());
  }
  EXPECT_EQ(copied_types, types);
  const googlesql::Type* proto =
      copy->FindTable("t")->FindColumn("p")->GetType();
  ASSERT_TRUE(proto->IsProto());
  EXPECT_EQ(proto->AsProto()->descriptor(),
            copy->proto_bundle()
                ->GetTypeDescriptor("emulator.tests.common.Simple")
                .value());
}

TEST(SchemaCreateCacheKeyTest, KeyCoversTheWholeRequest) {
  absl::FlagSaver flag_saver;
  auto key = [](const SchemaChangeOperation& operation) {
    return SchemaCreateCache::Key(operation,
                                  SchemaCreateCache::CurrentSettings());
  };
  const std::vector<std::string> statements = {"CREATE TABLE t (k INT64) "
                                               "PRIMARY KEY (k)"};
  SchemaChangeOperation base{.statements = statements};
  const std::string base_key = key(base);
  EXPECT_EQ(key(base), base_key);

  const std::vector<std::string> split = {"CREATE TABLE t (k INT64)",
                                          " PRIMARY KEY (k)"};
  EXPECT_NE(key(SchemaChangeOperation{.statements = split}), base_key);
  EXPECT_NE(key(SchemaChangeOperation{
                .statements = statements,
                .database_dialect = database_api::DatabaseDialect::POSTGRESQL}),
            base_key);
  EXPECT_NE(key(SchemaChangeOperation{.statements = statements,
                                      .proto_descriptor_bytes = "x"}),
            base_key);

  // Command-line flags, such as the one DDL validation reads for change
  // stream retention, and a GoogleSQL analyzer flag.
  absl::SetFlag(&FLAGS_cloud_spanner_emulator_disable_cs_retention_check,
                true);
  const std::string retention_key = key(base);
  EXPECT_NE(retention_key, base_key);
  absl::SetFlag(&FLAGS_cloud_spanner_emulator_disable_cs_retention_check,
                false);
  EXPECT_EQ(key(base), base_key);
  absl::CommandLineFlag* googlesql_flag = absl::FindCommandLineFlag(
      "googlesql_min_length_required_for_edit_distance");
  ASSERT_NE(googlesql_flag, nullptr);
  std::string error;
  ASSERT_TRUE(googlesql_flag->ParseFrom("1000", &error)) << error;
  EXPECT_NE(key(base), base_key);
  ASSERT_TRUE(
      googlesql_flag->ParseFrom(googlesql_flag->DefaultValue(), &error));
  EXPECT_EQ(key(base), base_key);

  // The flags the emulator writes at runtime and DDL never reads are not.
  absl::SetFlag(&FLAGS_change_stream_churning_interval, absl::Seconds(7));
  EXPECT_EQ(key(base), base_key);

  EmulatorFeatureFlags::Flags flags;
  flags.enable_identity_columns = false;
  test::ScopedEmulatorFeatureFlagsSetter setter(flags);
  EXPECT_NE(key(base), base_key);
}

// A create publishes its schema only if the settings it was keyed by held
// throughout: any write to the feature flags during the create, even one undone
// before it ends, and a command-line flag still changed at its end, mean the
// DDL may have read other settings than the key's.
class SchemaCreateCacheInterleavingTest : public ::testing::Test {
 protected:
  void SetUp() override {
    previous_ = SchemaCreateCache::SetGlobalForTesting(&cache_);
  }
  void TearDown() override {
    SchemaCreateCache::SetCreateHooksForTesting(nullptr, nullptr);
    EmulatorFeatureFlags::SetAfterSetHookForTesting(nullptr);
    SchemaCreateCache::SetGlobalForTesting(previous_);
    const_cast<EmulatorFeatureFlags&>(EmulatorFeatureFlags::instance())
        .set_flags(original_flags_);
  }

  absl::Status Create(const std::vector<std::string>& statements,
                      bool use_cache = true) {
    SchemaCreateCache* cache =
        SchemaCreateCache::SetGlobalForTesting(use_cache ? &cache_ : nullptr);
    absl::Status status =
        Database::Create(&clock_, "db",
                         SchemaChangeOperation{.statements = statements})
            .status();
    SchemaCreateCache::SetGlobalForTesting(cache);
    return status;
  }

  // Retention below a day is valid only while the check is disabled.
  const std::vector<std::string> retention_ddl_ = {
      "CREATE TABLE t (k INT64) PRIMARY KEY (k)",
      "CREATE CHANGE STREAM cs FOR t OPTIONS (retention_period = '1h')"};
  // Valid only while views are enabled.
  const std::vector<std::string> view_ddl_ = {
      "CREATE VIEW v SQL SECURITY INVOKER AS SELECT 1 AS a"};

  absl::FlagSaver flag_saver_;
  const EmulatorFeatureFlags::Flags original_flags_ =
      EmulatorFeatureFlags::instance().flags();
  Clock clock_;
  SchemaCreateCache cache_{4};
  SchemaCreateCache* previous_ = nullptr;
};

void SetRetentionCheckDisabled(bool disabled) {
  absl::SetFlag(&FLAGS_cloud_spanner_emulator_disable_cs_retention_check,
                disabled);
}

void SetViewsEnabled(bool enabled) {
  EmulatorFeatureFlags::Flags flags = EmulatorFeatureFlags::instance().flags();
  flags.enable_views = enabled;
  const_cast<EmulatorFeatureFlags&>(EmulatorFeatureFlags::instance())
      .set_flags(flags);
}

TEST_F(SchemaCreateCacheInterleavingTest, UnchangedSettingsPublish) {
  SetRetentionCheckDisabled(true);
  GOOGLESQL_ASSERT_OK(Create(retention_ddl_));
  EXPECT_EQ(cache_.size(), 1);
  EXPECT_EQ(cache_.rejected(), 0);
}

TEST_F(SchemaCreateCacheInterleavingTest, FlagChangedMidCreate) {
  SetRetentionCheckDisabled(false);
  SchemaCreateCache::SetCreateHooksForTesting(
      [] { SetRetentionCheckDisabled(true); }, nullptr);
  GOOGLESQL_EXPECT_OK(Create(retention_ddl_));
  SchemaCreateCache::SetCreateHooksForTesting(nullptr, nullptr);
  EXPECT_EQ(cache_.rejected(), 1);
  EXPECT_EQ(cache_.size(), 0);
}

TEST_F(SchemaCreateCacheInterleavingTest,
       FeatureFlagChangedAndRestoredMidCreate) {
  SetViewsEnabled(false);
  const absl::Status uncached = Create(view_ddl_, /*use_cache=*/false);
  ASSERT_FALSE(uncached.ok());

  SchemaCreateCache::SetCreateHooksForTesting([] { SetViewsEnabled(true); },
                                              [] { SetViewsEnabled(false); });
  GOOGLESQL_EXPECT_OK(Create(view_ddl_));
  SchemaCreateCache::SetCreateHooksForTesting(nullptr, nullptr);
  EXPECT_EQ(cache_.rejected(), 1);
  EXPECT_EQ(cache_.size(), 0);
  EXPECT_EQ(Create(view_ddl_), uncached);
}

// Two writers of the feature flags, each paused just after its write became
// visible: the first enables views before the DDL runs, the second disables
// them again before the create checks the settings. The flags then equal the
// key's, but they were written twice, so the schema is not published.
TEST_F(SchemaCreateCacheInterleavingTest,
       TwoWritersRestoreFeatureFlagsMidCreate) {
  SetViewsEnabled(false);
  const absl::Status uncached = Create(view_ddl_, /*use_cache=*/false);
  ASSERT_FALSE(uncached.ok());

  absl::Notification paused[2];
  absl::Notification release[2];
  std::atomic<int> writes = 0;
  EmulatorFeatureFlags::SetAfterSetHookForTesting([&] {
    const int i = writes++;
    paused[i].Notify();
    release[i].WaitForNotification();
  });
  std::vector<std::thread> writers;
  auto write = [&](bool views) {
    const int i = writers.size();
    writers.emplace_back([views] { SetViewsEnabled(views); });
    paused[i].WaitForNotification();
  };
  SchemaCreateCache::SetCreateHooksForTesting([&] { write(true); },
                                              [&] { write(false); });
  GOOGLESQL_EXPECT_OK(Create(view_ddl_));
  SchemaCreateCache::SetCreateHooksForTesting(nullptr, nullptr);
  for (absl::Notification& notification : release) notification.Notify();
  for (std::thread& writer : writers) writer.join();
  EmulatorFeatureFlags::SetAfterSetHookForTesting(nullptr);

  EXPECT_EQ(cache_.rejected(), 1);
  EXPECT_EQ(cache_.size(), 0);
  EXPECT_EQ(Create(view_ddl_), uncached);
}

TEST(SchemaCreateCacheLruTest, EvictsTheLeastRecentlyUsed) {
  SchemaCreateCache cache(2);
  auto entry = [] { return std::make_shared<SchemaCreateCache::Entry>(); };
  cache.Insert("a", entry());
  cache.Insert("b", entry());
  EXPECT_NE(cache.Lookup("a"), nullptr);  // a is now the most recent
  cache.Insert("c", entry());
  EXPECT_EQ(cache.Lookup("b"), nullptr);
  EXPECT_NE(cache.Lookup("a"), nullptr);
  EXPECT_NE(cache.Lookup("c"), nullptr);
  EXPECT_EQ(cache.size(), 2);
  EXPECT_EQ(cache.hits(), 3);
  EXPECT_EQ(cache.misses(), 1);
}

}  // namespace
}  // namespace backend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
